version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
      # - image: circleci/node:6-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test

      # deploy
      - run:
          name: Avoid hosts unknown for github
          command: ssh-keyscan planninglabs.nyc >> ~/.ssh/known_hosts
      - deploy:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git remote add dokku dokku@planninglabs.nyc:applicantmaps && git push dokku master
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              git remote add dokku dokku@planninglabs.nyc:applicantmaps-staging && git push dokku develop:master
            fi